# Generated by Django 5.2.16 on 2026-07-29 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('description', models.CharField(max_length=180, unique=True)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['description'],
                'constraints': [models.UniqueConstraint(fields=('description', 'sector'), name='unique_location_description_sector')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=16)),
                ('parts_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='assets.equipment')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='assets.equipmentfamily')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='assets.location')),
            ],
            options={
                'ordering': ['description'],
                'indexes': [models.Index(fields=['status', 'description'], name='assets_equi_status_f91784_idx'), models.Index(fields=['location', 'description'], name='assets_equi_locatio_bd68b5_idx')],
            },
        ),
    ]
