# Generated by Django 5.2.16 on 2026-07-29 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('purchase_code', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('unit', 'Unidade'), ('liter', 'Litro'), ('meter', 'Metro'), ('square_meter', 'Metro quadrado'), ('cubic_meter', 'Metro cubico'), ('hour', 'Hora')], max_length=24)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purchased_on', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
