# Generated by Django 5.2.16 on 2026-07-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='maintenance.costcenter'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['active', 'name'], name='inventory_m_active_6daedb_idx'),
        ),
    ]
