# Generated by Django 5.2.16 on 2026-07-30 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier_tax_id',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.CreateModel(
            name='NfeImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_key', models.CharField(blank=True, max_length=44, null=True, unique=True)),
                ('document_hash', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=180)),
                ('supplier_tax_id', models.CharField(blank=True, max_length=14)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NfeUnitMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_unit', models.CharField(max_length=32, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('unit', 'Unidade'), ('liter', 'Litro'), ('meter', 'Metro'), ('square_meter', 'Metro quadrado'), ('cubic_meter', 'Metro cubico'), ('hour', 'Hora')], max_length=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_unit_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_unit'],
            },
        ),
    ]
