# Generated by Django 5.2.16 on 2026-07-29 12:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('inventory', '0001_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('description', models.CharField(max_length=180, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
            ],
            options={
                'ordering': ['description'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('description', models.CharField(max_length=180, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['description'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('description', models.CharField(max_length=180, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['description'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('description', models.CharField(max_length=180, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#64748B', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor hexadecimal no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderSequence',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('current_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('description', models.CharField(max_length=180, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('requester', models.CharField(blank=True, max_length=180)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('machine_stopped', models.BooleanField(default=True)),
                ('manual_downtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('downtime_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('defect_description', models.TextField(blank=True)),
                ('services_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('materials_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('outsourced_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.maintenancearea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.maintenancetype')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.priority')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutsourcedService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outsourced_services', to='maintenance.costcenter')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_services', to='workforce.serviceprovider')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsourced_services', to='maintenance.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_costs', to='maintenance.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_name', models.CharField(max_length=180)),
                ('location_name', models.CharField(blank=True, max_length=180)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_links', to='assets.equipment')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_links', to='maintenance.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='equipment',
            field=models.ManyToManyField(related_name='work_orders', through='maintenance.WorkOrderEquipment', to='assets.equipment'),
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_code', models.CharField(max_length=80)),
                ('material_name', models.CharField(max_length=180)),
                ('unit', models.CharField(max_length=24)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_usage', to='inventory.material')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='maintenance.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.workorderstatus'),
        ),
        migrations.CreateModel(
            name='WorkOrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='maintenance.workorderstatus')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.TextField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='maintenance.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceMaintainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hourly_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_assignments', to='workforce.maintainer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainers', to='maintenance.workservice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workorderequipment',
            constraint=models.UniqueConstraint(fields=('work_order', 'equipment'), name='unique_work_order_equipment'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', '-created_at'], name='maintenance_status__46af0c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['scheduled_at'], name='maintenance_schedul_6817c6_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority', 'status'], name='maintenance_priorit_7b753c_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicemaintainer',
            constraint=models.UniqueConstraint(fields=('service', 'maintainer'), name='unique_service_maintainer'),
        ),
    ]
