# Generated by Django 5.2.16 on 2026-07-29 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maintenance', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderequipment',
            name='hierarchy',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('category', models.CharField(choices=[('image', 'Imagem'), ('document', 'Documento'), ('file', 'Arquivo')], default='file', max_length=16)),
                ('url', models.URLField(max_length=1000)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('media_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='maintenance_content_3bab85_idx')],
            },
        ),
    ]
