# Generated by Django 5.2.16 on 2026-07-29 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_workorderequipment_hierarchy_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('notification_type', models.CharField(choices=[('nova_solicitacao', 'Nova solicitacao'), ('os_atualizada', 'OS atualizada')], max_length=32)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='maintenance_is_read_ce33ad_idx')],
            },
        ),
    ]
