# Generated by Django 5.2.16 on 2026-07-30 12:17

import django.db.models.deletion
import unicodedata
from django.conf import settings
from django.db import migrations, models


def normalize_label(value):
    normalized = unicodedata.normalize("NFD", str(value or ""))
    return "".join(char for char in normalized if not unicodedata.combining(char)).casefold().strip()


def classify_dashboard_references(apps, schema_editor):
    MaintenanceType = apps.get_model("maintenance", "MaintenanceType")
    Priority = apps.get_model("maintenance", "Priority")
    WorkOrder = apps.get_model("maintenance", "WorkOrder")
    WorkOrderStatus = apps.get_model("maintenance", "WorkOrderStatus")
    WorkOrderStatusHistory = apps.get_model("maintenance", "WorkOrderStatusHistory")

    status_rules = {
        "aberta": ("open", True, False, 10),
        "em andamento": ("in_progress", False, False, 20),
        "aguardando pecas": ("waiting_parts", False, False, 30),
        "aguardando nf": ("waiting_document", False, False, 35),
        "concluida": ("completed", False, True, 40),
        "cancelada": ("cancelled", False, True, 50),
        "reprovada": ("rejected", False, True, 60),
    }
    grouped_statuses = {}
    for status in WorkOrderStatus.objects.all():
        grouped_statuses.setdefault(normalize_label(status.description), []).append(status)

    for label, statuses in grouped_statuses.items():
        category, is_initial, is_final, order = status_rules.get(
            label,
            ("other", False, False, 100),
        )
        canonical = max(
            statuses,
            key=lambda item: (
                item.order > 0,
                item.is_initial or item.is_final,
                item.order,
            ),
        )
        WorkOrder.objects.filter(status_id__in=[item.pk for item in statuses]).update(
            status=canonical
        )
        WorkOrderStatusHistory.objects.filter(
            status_id__in=[item.pk for item in statuses]
        ).update(status=canonical)
        WorkOrderStatus.objects.filter(pk=canonical.pk).update(
            category=category,
            is_initial=is_initial,
            is_final=is_final,
            order=order,
            active=True,
        )
        WorkOrderStatus.objects.filter(
            pk__in=[item.pk for item in statuses if item.pk != canonical.pk]
        ).update(
            category=category,
            is_initial=False,
            is_final=is_final,
            active=False,
        )

    type_rules = {
        "corretiva": "corrective",
        "preventiva": "preventive",
        "preditiva": "predictive",
        "emergencial": "emergency",
        "melhoria": "improvement",
        "realocacao": "relocation",
        "tercerizada": "outsourced",
        "terceirizada": "outsourced",
    }
    for maintenance_type in MaintenanceType.objects.all():
        MaintenanceType.objects.filter(pk=maintenance_type.pk).update(
            category=type_rules.get(
                normalize_label(maintenance_type.description),
                "other",
            )
        )

    priority_rules = {
        "baixa": "low",
        "normal": "normal",
        "media": "normal",
        "alta": "high",
        "critica": "critical",
        "emergencia": "emergency",
    }
    for priority in Priority.objects.all():
        Priority.objects.filter(pk=priority.pk).update(
            severity=priority_rules.get(
                normalize_label(priority.description),
                "normal",
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_equipment_serial_number'),
        ('maintenance', '0008_workservice_identified_defect'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetype',
            name='category',
            field=models.CharField(choices=[('corrective', 'Corretiva'), ('preventive', 'Preventiva'), ('predictive', 'Preditiva'), ('emergency', 'Emergencial'), ('improvement', 'Melhoria'), ('relocation', 'Realocacao'), ('outsourced', 'Terceirizada'), ('other', 'Outra')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='priority',
            name='severity',
            field=models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Critica'), ('emergency', 'Emergencia')], db_index=True, default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to='workforce.maintainer'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderstatus',
            name='category',
            field=models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em andamento'), ('waiting_parts', 'Aguardando pecas'), ('waiting_document', 'Aguardando documento'), ('completed', 'Concluida'), ('cancelled', 'Cancelada'), ('rejected', 'Reprovada'), ('other', 'Outra')], db_index=True, default='other', max_length=24),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['approval_status', 'due_at'], name='maintenance_approva_ce4f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_maintainer', 'status'], name='maintenance_assigne_954076_idx'),
        ),
        migrations.RunPython(
            classify_dashboard_references,
            migrations.RunPython.noop,
        ),
    ]
