BACKUP_FORMAT_VERSION = "1"

ENTITY_FIELDS = {
    "OrdemServico": [
        "id",
        "numero",
        "equipamento_id",
        "equipamento_nome",
        "equipamento_descricao_livre",
        "equipamento_nao_cadastrado",
        "equipamentos",
        "local",
        "localizacao_celula",
        "localizacao_setor",
        "tipo_id",
        "tipo_nome",
        "status_id",
        "status_nome",
        "area_id",
        "area_nome",
        "prioridade_id",
        "prioridade_nome",
        "solicitante",
        "data_programada",
        "hora_programada",
        "data_prazo",
        "hora_prazo",
        "data_finalizada",
        "hora_finalizada",
        "responsavel_id",
        "responsavel_nome",
        "maquina_parada",
        "tempo_parada_manual",
        "observacoes",
        "descricao_defeito",
        "servicos",
        "materiais",
        "terceirizados",
        "outros",
        "valor_total_servicos",
        "valor_total_materiais",
        "valor_total_terceirizados",
        "valor_total_outros",
        "valor_total_geral",
        "tempo_parado_em_minutos",
        "aprovacao_status",
        "motivo_recusa",
        "data_aprovacao",
        "anexos",
        "created_date",
        "updated_date",
    ],
    "Equipamento": [
        "id",
        "codigo",
        "descricao",
        "marca",
        "modelo",
        "fabricante",
        "numero_serie",
        "localizacao_id",
        "localizacao_celula",
        "localizacao_setor",
        "familia_id",
        "status",
        "parent_id",
        "pecas_por_hora",
        "imagens",
        "componentes",
        "created_date",
        "updated_date",
    ],
    "Material": [
        "id",
        "codigo",
        "codigo_compra",
        "nome",
        "unidade_medida",
        "custo",
        "centro_custo",
        "fornecedor",
        "fornecedor_cnpj",
        "data_compra",
        "created_date",
        "updated_date",
    ],
    "Mantenedor": [
        "id",
        "nome",
        "cargo",
        "custo_hora",
        "created_date",
        "updated_date",
    ],
    "TipoManutencao": [
        "id",
        "descricao",
        "categoria",
        "created_date",
        "updated_date",
    ],
    "StatusOS": [
        "id",
        "descricao",
        "categoria",
        "inicial",
        "final",
        "ordem",
        "created_date",
        "updated_date",
    ],
    "AreaManutencao": ["id", "descricao", "created_date", "updated_date"],
    "FamiliaEquipamento": ["id", "descricao", "created_date", "updated_date"],
    "PrestadoraServico": [
        "id",
        "nome_empresa",
        "cnpj",
        "contato1",
        "contato2",
        "email",
        "servicos_prestados",
        "created_date",
        "updated_date",
    ],
    "Localizacao": [
        "id",
        "descricao",
        "setor",
        "observacoes",
        "created_date",
        "updated_date",
    ],
    "Prioridade": [
        "id",
        "descricao",
        "cor",
        "ordem",
        "severidade",
        "created_date",
        "updated_date",
    ],
    "CentroCusto": [
        "id",
        "descricao",
        "codigo",
        "created_date",
        "updated_date",
    ],
    "NotificacaoOS": [
        "id",
        "ordem_servico_id",
        "tipo_notificacao",
        "mensagem",
        "foi_lida",
        "data_leitura",
        "created_date",
        "updated_date",
    ],
}

LEGACY_ENTITY_NAMES = tuple(ENTITY_FIELDS)
