# Generated by Django 5.2.16 on 2026-07-29 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('position', models.CharField(max_length=120)),
                ('hourly_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, help_text='Identificador da entidade no backend legado.', max_length=64, null=True, unique=True)),
                ('company_name', models.CharField(max_length=180)),
                ('tax_id', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('primary_phone', models.CharField(blank=True, max_length=32)),
                ('secondary_phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('services_description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
